-- ============================================================
-- MDCCCVII TESTS — CANONICAL DATABASE MIGRATION V10
-- Run AFTER the original project setup, ONCE.
-- This replaces the need to run ADMIN-V6.sql / ADMIN-V7.sql /
-- LEADERBOARD.sql separately.
-- ============================================================

-- ---------- TEST POLICY ----------
alter table public.tests
  add column if not exists reattempt_limit integer not null default 0,
  add column if not exists leaderboard_enabled boolean not null default true,
  add column if not exists archived boolean not null default false;

alter table public.tests drop constraint if exists tests_reattempt_limit_check;
alter table public.tests add constraint tests_reattempt_limit_check check (reattempt_limit between 0 and 50);

-- ---------- SERVER-OWNED ATTEMPT SNAPSHOT ----------
alter table public.attempts
  add column if not exists expires_at timestamptz,
  add column if not exists duration_minutes_snapshot integer,
  add column if not exists total_questions_snapshot integer,
  add column if not exists positive_marks_snapshot numeric,
  add column if not exists negative_mcq_snapshot numeric,
  add column if not exists negative_numerical_snapshot numeric;

-- ---------- EXTRA ATTEMPT GRANTS ----------
create table if not exists public.attempt_grants(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  test_id bigint not null references public.tests(id) on delete cascade,
  remaining integer not null default 1 check (remaining >= 0),
  note text,
  created_at timestamptz not null default now()
);
alter table public.attempt_grants enable row level security;

-- ---------- ADMIN AUDIT LOG ----------
create table if not exists public.admin_audit_log(
  id bigint generated by default as identity primary key,
  admin_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.admin_audit_log enable row level security;

-- ---------- INDEXES ----------
create index if not exists idx_attempts_user_test_status on public.attempts(user_id,test_id,status);
create index if not exists idx_attempts_expires on public.attempts(expires_at) where status='in_progress';
create index if not exists idx_attempts_submitted on public.attempts(submitted_at) where status='submitted';
create index if not exists idx_attempt_grants_user_test on public.attempt_grants(user_id,test_id,remaining);
create index if not exists idx_audit_created on public.admin_audit_log(created_at desc);

-- ---------- ATTEMPT LIMIT + IMMUTABLE SNAPSHOT ----------
drop trigger if exists trg_guard_test_attempt_limit on public.attempts;

-- attempts.id is bigint: remove old uuid-typed overloads (they break PostgREST rpc)
drop function if exists public.save_attempt_answers(uuid,jsonb);
drop function if exists public.get_attempt_resume(uuid);
drop function if exists public.submit_test_attempt(uuid,jsonb);
drop function if exists public.admin_force_submit(uuid,text);
drop function if exists public.admin_invalidate_attempt(uuid,text);
drop function if exists public.start_test_attempt(bigint);
create or replace function public.start_test_attempt(p_test_id bigint)
returns table(
  id bigint,
  test_id bigint,
  started_at timestamptz,
  expires_at timestamptz,
  duration_minutes integer,
  total_questions integer,
  positive_marks numeric,
  negative_mcq numeric,
  negative_numerical numeric,
  max_score numeric
)
language plpgsql security definer set search_path=public as $$
#variable_conflict use_column
declare
  v_uid uuid := auth.uid();
  t public.tests%rowtype;
  used_count integer;
  base_limit integer;
  grant_id bigint;
  grant_remaining integer;
  new_id bigint;
  started timestamptz := now();
  expires timestamptz;
begin
  if v_uid is null then raise exception 'Please sign in before starting a test.'; end if;

  select * into t from public.tests where id=p_test_id for update;
  if not found or coalesce(t.enabled,false)=false or coalesce(t.archived,false)=true then
    raise exception 'This test is not available.';
  end if;
  if t.release_at > now() then raise exception 'This test has not started yet.'; end if;
  if exists(select 1 from public.profiles p where p.id=v_uid and coalesce(p.blocked,false)) then
    raise exception 'Your student account is blocked. You cannot start a new test.';
  end if;

  select count(*) into used_count from public.attempts a
  where a.user_id=v_uid and a.test_id=p_test_id and a.status in ('in_progress','submitted');
  base_limit := 1 + coalesce(t.reattempt_limit,0);

  if used_count >= base_limit then
    select g.id,g.remaining into grant_id,grant_remaining
    from public.attempt_grants g
    where g.user_id=v_uid and g.test_id=p_test_id and g.remaining>0
    order by g.created_at asc, g.id asc limit 1 for update;
    if grant_id is null then
      raise exception 'Attempt limit reached. This paper allows % total attempt(s).', base_limit;
    end if;
    update public.attempt_grants set remaining=remaining-1 where id=grant_id;
  end if;

  expires := started + (coalesce(t.duration_minutes,180) * interval '1 minute');
  perform set_config('app.authorized_attempt_start','1',true);
  insert into public.attempts(
    user_id,test_id,status,max_score,started_at,created_at,expires_at,
    duration_minutes_snapshot,total_questions_snapshot,positive_marks_snapshot,
    negative_mcq_snapshot,negative_numerical_snapshot
  ) values (
    v_uid,p_test_id,'in_progress',coalesce(t.total_marks,t.total_questions*coalesce(t.positive_marks,4)),
    started,started,expires,coalesce(t.duration_minutes,180),t.total_questions,
    coalesce(t.positive_marks,4),coalesce(t.negative_mcq,1),coalesce(t.negative_numerical,1)
  ) returning attempts.id into new_id;

  return query select new_id,p_test_id,started,expires,coalesce(t.duration_minutes,180),
    t.total_questions,coalesce(t.positive_marks,4),coalesce(t.negative_mcq,1),
    coalesce(t.negative_numerical,1),coalesce(t.total_marks,t.total_questions*coalesce(t.positive_marks,4));
end; $$;
grant execute on function public.start_test_attempt(bigint) to authenticated;

-- Prevent direct client INSERT from bypassing the server policy.
create or replace function public.guard_test_attempt_limit()
returns trigger language plpgsql security definer set search_path=public as $$
declare lim integer; used integer;
begin
  if current_setting('app.authorized_attempt_start',true)='1' then return new; end if;
  select 1+coalesce(reattempt_limit,0) into lim from public.tests where id=new.test_id;
  select count(*) into used from public.attempts where user_id=new.user_id and test_id=new.test_id and status in ('in_progress','submitted');
  if used >= coalesce(lim,1) then raise exception 'Attempt creation must use the secure start-test flow.'; end if;
  return new;
end; $$;
create trigger trg_guard_test_attempt_limit before insert on public.attempts for each row execute function public.guard_test_attempt_limit();

-- ---------- IMMUTABLE TEST SETTINGS AFTER FIRST ATTEMPT ----------
create or replace function public.guard_test_version_changes()
returns trigger language plpgsql security definer set search_path=public as $$
declare n integer;
begin
  select count(*) into n from public.attempts where test_id=old.id;
  if n>0 and (
    new.duration_minutes is distinct from old.duration_minutes or
    new.total_questions is distinct from old.total_questions or
    new.total_marks is distinct from old.total_marks or
    new.positive_marks is distinct from old.positive_marks or
    new.negative_mcq is distinct from old.negative_mcq or
    new.negative_numerical is distinct from old.negative_numerical or
    new.paper_url is distinct from old.paper_url
  ) then
    raise exception 'This test already has attempts. Scoring settings and question paper are locked. Create a new test/version instead.';
  end if;
  return new;
end; $$;
drop trigger if exists trg_guard_test_version_changes on public.tests;
create trigger trg_guard_test_version_changes before update on public.tests for each row execute function public.guard_test_version_changes();

-- ---------- ANSWER AUTOSAVE ----------
create or replace function public.save_attempt_answers(p_attempt_id bigint,p_answers jsonb)
returns boolean language plpgsql security definer set search_path=public as $$
declare a public.attempts%rowtype; row jsonb;
begin
  select * into a from public.attempts where id=p_attempt_id and user_id=auth.uid() for update;
  if not found then raise exception 'Attempt not found.'; end if;
  if a.status <> 'in_progress' then raise exception 'This attempt is already closed.'; end if;
  if a.expires_at is not null and a.expires_at <= now() then raise exception 'The exam time has expired.'; end if;

  for row in select * from jsonb_array_elements(coalesce(p_answers,'[]'::jsonb)) loop
    insert into public.answers(attempt_id,question_no,response,marked_for_review,answered_at)
    values(a.id,(row->>'question_no')::integer,nullif(row->>'response',''),coalesce((row->>'marked_for_review')::boolean,false),case when nullif(row->>'response','') is null then null else now() end)
    on conflict(attempt_id,question_no) do update set
      response=excluded.response,
      marked_for_review=excluded.marked_for_review,
      answered_at=excluded.answered_at;
  end loop;
  return true;
end; $$;
grant execute on function public.save_attempt_answers(bigint,jsonb) to authenticated;

-- ---------- SERVER RESUME ----------
drop function if exists public.get_attempt_resume(bigint);
create or replace function public.get_attempt_resume(p_attempt_id bigint)
returns table(
  id bigint,test_id bigint,status text,started_at timestamptz,expires_at timestamptz,
  duration_minutes integer,total_questions integer,positive_marks numeric,negative_mcq numeric,
  negative_numerical numeric,answers jsonb
)
language sql security definer set search_path=public stable as $$
select a.id,a.test_id,a.status,a.started_at,a.expires_at,a.duration_minutes_snapshot,
       a.total_questions_snapshot,a.positive_marks_snapshot,a.negative_mcq_snapshot,
       a.negative_numerical_snapshot,
       coalesce((select jsonb_agg(jsonb_build_object('question_no',x.question_no,'response',x.response,'marked_for_review',x.marked_for_review) order by x.question_no) from public.answers x where x.attempt_id=a.id),'[]'::jsonb)
from public.attempts a
where a.id=p_attempt_id and a.user_id=auth.uid() and a.status='in_progress';
$$;
grant execute on function public.get_attempt_resume(bigint) to authenticated;

-- ---------- ATOMIC SUBMISSION ----------
drop function if exists public.submit_test_attempt(bigint,jsonb);
create or replace function public.submit_test_attempt(p_attempt_id bigint,p_answers jsonb)
returns table(id bigint,status text,submitted_at timestamptz,time_taken_seconds bigint)
language plpgsql security definer set search_path=public as $$
#variable_conflict use_column
declare a public.attempts%rowtype; submitted timestamptz:=now(); elapsed bigint; row jsonb;
begin
  select * into a from public.attempts where id=p_attempt_id and user_id=auth.uid() for update;
  if not found then raise exception 'Attempt not found.'; end if;
  if a.status='submitted' then return query select a.id,a.status,a.submitted_at,a.time_taken_seconds; return; end if;
  if a.status <> 'in_progress' then raise exception 'This attempt cannot be submitted.'; end if;

  -- Final answer write intentionally does NOT reject an expired attempt.
  -- The server records the answers and caps elapsed time at the authoritative expiry.
  for row in select * from jsonb_array_elements(coalesce(p_answers,'[]'::jsonb)) loop
    insert into public.answers(attempt_id,question_no,response,marked_for_review,answered_at)
    values(a.id,(row->>'question_no')::integer,nullif(row->>'response',''),coalesce((row->>'marked_for_review')::boolean,false),case when nullif(row->>'response','') is null then null else now() end)
    on conflict(attempt_id,question_no) do update set response=excluded.response,marked_for_review=excluded.marked_for_review,answered_at=excluded.answered_at;
  end loop;
  elapsed := greatest(0,extract(epoch from (least(now(),coalesce(a.expires_at,now()))-a.started_at))::bigint);
  update public.attempts set status='submitted',submitted_at=submitted,unanswered_count=greatest(0,coalesce(a.total_questions_snapshot,0)-(select count(*) from public.answers where attempt_id=a.id and response is not null and response<>'')),time_taken_seconds=elapsed where id=a.id;
  return query select a.id,'submitted'::text,submitted,elapsed;
end; $$;
grant execute on function public.submit_test_attempt(bigint,jsonb) to authenticated;

-- ---------- ADMIN HELPERS ----------
create or replace function public.admin_update_student(p_user_id uuid,p_name text,p_blocked boolean)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Admins only'; end if;
  update public.profiles set name=trim(p_name),blocked=coalesce(p_blocked,false) where id=p_user_id;
  if not found then raise exception 'Student profile not found'; end if;
  insert into public.admin_audit_log(admin_user_id,action,target_type,target_id,details) values(auth.uid(),'student_update','student',p_user_id::text,jsonb_build_object('name',p_name,'blocked',p_blocked));
  return true;
end; $$;
grant execute on function public.admin_update_student(uuid,text,boolean) to authenticated;

create or replace function public.admin_grant_attempt(p_user_id uuid,p_test_id bigint,p_count integer default 1,p_note text default null)
returns integer language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Admins only'; end if;
  if p_count<1 or p_count>20 then raise exception 'Grant must be between 1 and 20 attempts.'; end if;
  insert into public.attempt_grants(user_id,test_id,remaining,note) values(p_user_id,p_test_id,p_count,p_note);
  insert into public.admin_audit_log(admin_user_id,action,target_type,target_id,details) values(auth.uid(),'grant_attempt','student',p_user_id::text,jsonb_build_object('test_id',p_test_id,'count',p_count,'note',p_note));
  return p_count;
end; $$;
grant execute on function public.admin_grant_attempt(uuid,bigint,integer,text) to authenticated;

create or replace function public.admin_force_submit(p_attempt_id bigint,p_reason text default null)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Admins only'; end if;
  update public.attempts set status='submitted',submitted_at=coalesce(submitted_at,now()),time_taken_seconds=greatest(0,extract(epoch from (least(now(),coalesce(expires_at,now()))-started_at))::bigint) where id=p_attempt_id and status='in_progress';
  insert into public.admin_audit_log(admin_user_id,action,target_type,target_id,details) values(auth.uid(),'force_submit','attempt',p_attempt_id::text,jsonb_build_object('reason',p_reason));
  return true;
end; $$;
grant execute on function public.admin_force_submit(bigint,text) to authenticated;

create or replace function public.admin_invalidate_attempt(p_attempt_id bigint,p_reason text default null)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Admins only'; end if;
  update public.attempts set status='invalidated' where id=p_attempt_id;
  insert into public.admin_audit_log(admin_user_id,action,target_type,target_id,details) values(auth.uid(),'invalidate_attempt','attempt',p_attempt_id::text,jsonb_build_object('reason',p_reason));
  return true;
end; $$;
grant execute on function public.admin_invalidate_attempt(bigint,text) to authenticated;

create or replace function public.admin_archive_test(p_test_id bigint)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Admins only'; end if;
  update public.tests set archived=true,enabled=false where id=p_test_id;
  insert into public.admin_audit_log(admin_user_id,action,target_type,target_id,details) values(auth.uid(),'archive_test','test',p_test_id::text,'{}'::jsonb);
  return true;
end; $$;
grant execute on function public.admin_archive_test(bigint) to authenticated;

drop function if exists public.admin_test_stats(bigint);
create or replace function public.admin_test_stats(p_test_id bigint)
returns table(attempts bigint,submitted bigint,in_progress bigint,invalidated bigint,avg_score numeric,median_score numeric,highest_score numeric,avg_time_seconds numeric)
language sql security definer set search_path=public stable as $$
select count(*),count(*) filter(where status='submitted'),count(*) filter(where status='in_progress'),count(*) filter(where status='invalidated'),avg(score) filter(where status='submitted'),percentile_cont(.5) within group(order by score) filter(where status='submitted'),max(score) filter(where status='submitted'),avg(time_taken_seconds) filter(where status='submitted') from public.attempts where test_id=p_test_id and public.is_admin();
$$;
grant execute on function public.admin_test_stats(bigint) to authenticated;

-- ---------- LEADERBOARD: FIRST ATTEMPT ONLY, RE-ATTEMPTS HIDDEN ----------
drop function if exists public.get_leaderboard(bigint);
create or replace function public.get_leaderboard(p_test_id bigint default null)
returns table(rank bigint,user_id uuid,name text,photo_url text,score numeric,max_score numeric,correct_count bigint,time_taken_seconds bigint,tests_taken bigint,is_me boolean)
language sql security definer set search_path=public stable as $$
with ranked as(
 select a.*,row_number() over(partition by a.user_id,a.test_id order by a.submitted_at asc nulls last,a.created_at asc,a.id asc) rn
 from public.attempts a join public.tests t on t.id=a.test_id
 where a.status='submitted' and a.score is not null and t.enabled and not coalesce(t.archived,false) and coalesce(t.leaderboard_enabled,true) and exists(select 1 from public.test_keys k where k.test_id=a.test_id) and (p_test_id is null or a.test_id=p_test_id)
), firsts as(select * from ranked where rn=1), agg as(select user_id,sum(score) score,sum(max_score) max_score,sum(coalesce(correct_count,0)) cc,sum(coalesce(time_taken_seconds,0)) tt,count(*) n from firsts group by user_id)
select rank() over(order by g.score desc,g.tt asc),g.user_id,coalesce(nullif(p.name,''),'Student'),p.photo_url,g.score,g.max_score,g.cc,g.tt,g.n,g.user_id=auth.uid() from agg g left join public.profiles p on p.id=g.user_id order by 1,g.user_id;
$$;
grant execute on function public.get_leaderboard(bigint) to authenticated;

-- ---------- ADMIN AUDIT READ ----------
drop function if exists public.admin_audit(integer);
create or replace function public.admin_audit(limit_count integer default 100)
returns table(id bigint,admin_user_id uuid,action text,target_type text,target_id text,details jsonb,created_at timestamptz)
language sql security definer set search_path=public stable as $$
select l.id,l.admin_user_id,l.action,l.target_type,l.target_id,l.details,l.created_at from public.admin_audit_log l where public.is_admin() order by l.created_at desc limit greatest(1,least(limit_count,500));
$$;
grant execute on function public.admin_audit(integer) to authenticated;

-- ============================================================
-- END V10
-- ============================================================

-- ---------- CORRECT SCORING USES THE ATTEMPT SNAPSHOT ----------
create or replace function public.publish_answer_key(p_test_id bigint,p_key text)
returns integer language plpgsql security definer set search_path=public as $$
declare t public.tests%rowtype; ks text[]; per integer; n integer;
begin
  if not public.is_admin() then raise exception 'Admins only'; end if;
  select * into t from public.tests where id=p_test_id;
  if not found then raise exception 'Test not found.'; end if;
  select array_agg(case upper(x) when 'A' then '1' when 'B' then '2' when 'C' then '3' when 'D' then '4' else x end)
    into ks from unnest(regexp_split_to_array(trim(p_key),'[\s,;]+')) x where x<>'';
  if coalesce(array_length(ks,1),0)<>t.total_questions then raise exception 'Key has % answers but the test has % questions',coalesce(array_length(ks,1),0),t.total_questions; end if;
  insert into public.test_keys(test_id,keys) values(p_test_id,ks) on conflict(test_id) do update set keys=excluded.keys,published_at=now();
  perform set_config('app.eval','1',true);
  with g as(
    select an.attempt_id,
      sum(case when (case when ((an.question_no-1)%greatest(coalesce(a.total_questions_snapshot,1)/3,1)) >= greatest(coalesce(a.total_questions_snapshot,1)/3,1)-5 then case when an.response~'^-?\d+(\.\d+)?$' and ks[an.question_no]~'^-?\d+(\.\d+)?$' then abs(an.response::numeric-ks[an.question_no]::numeric)<1e-9 else false end else an.response=ks[an.question_no] end) then 1 else 0 end) c,
      sum(case when an.response is not null and an.response<>'' and not (case when ((an.question_no-1)%greatest(coalesce(a.total_questions_snapshot,1)/3,1)) >= greatest(coalesce(a.total_questions_snapshot,1)/3,1)-5 then case when an.response~'^-?\d+(\.\d+)?$' and ks[an.question_no]~'^-?\d+(\.\d+)?$' then abs(an.response::numeric-ks[an.question_no]::numeric)<1e-9 else false end else an.response=ks[an.question_no] end) then 1 else 0 end) w,
      sum(case when an.response is null or an.response='' then 0 when (case when ((an.question_no-1)%greatest(coalesce(a.total_questions_snapshot,1)/3,1)) >= greatest(coalesce(a.total_questions_snapshot,1)/3,1)-5 then case when an.response~'^-?\d+(\.\d+)?$' and ks[an.question_no]~'^-?\d+(\.\d+)?$' then abs(an.response::numeric-ks[an.question_no]::numeric)<1e-9 else false end else an.response=ks[an.question_no] end) then a.positive_marks_snapshot else -(case when ((an.question_no-1)%greatest(coalesce(a.total_questions_snapshot,1)/3,1)) >= greatest(coalesce(a.total_questions_snapshot,1)/3,1)-5 then a.negative_numerical_snapshot else a.negative_mcq_snapshot end) end) sc
    from public.answers an join public.attempts a on a.id=an.attempt_id
    where a.test_id=p_test_id and a.status='submitted'
    group by an.attempt_id
  )
  update public.attempts a set score=coalesce(g.sc,0),correct_count=g.c,incorrect_count=g.w from g where a.id=g.attempt_id;
  get diagnostics n=row_count; return n;
end; $$;
grant execute on function public.publish_answer_key(bigint,text) to authenticated;
