'use strict';
const SUPABASE_URL='https://grgxaewilmfyvndkcfim.supabase.co';
const SUPABASE_KEY='sb_publishable_aiJYxr3AYoeZHBXwIoXaaQ_gIfHxV2s';
const BUCKET='test-pdfs';
const {createClient}=window.supabase;
const db=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s); let session=null,current='overview',testsCache=[],studentsCache=[],attemptsCache=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(id){$(id).classList.remove('hidden')} function hide(id){$(id).classList.add('hidden')}
function toast(msg){$('#toast').textContent=msg;show('#toast');clearTimeout(window.__toast);window.__toast=setTimeout(()=>hide('#toast'),3000)}
function formatDate(v){return v?new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—'}
function statusFor(t){if(t.enabled===false)return ['DISABLED','disabled'];return new Date(t.release_at)<=new Date()?['RELEASED','released']:['SCHEDULED','scheduled']}
function localInput(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return '';return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
async function requireAdmin(){const {data,error}=await db.auth.getSession();if(error)throw error;session=data.session;if(!session){hide('#loading');show('#login');return false}const {data:isAdmin,error:e}=await db.rpc('is_admin');if(e)throw e;if(!isAdmin){hide('#loading');show('#login');$('#loginError').textContent='This Google account is not an admin.';show('#loginError');return false}hide('#loading');hide('#login');show('#app');$('#adminIdentity').textContent=session.user.email||session.user.user_metadata?.full_name||'Admin';return true}
async function signIn(){$('#googleBtn').disabled=true;hide('#loginError');const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(error){$('#loginError').textContent=error.message;show('#loginError');$('#googleBtn').disabled=false}}
async function loadAll(){const [p,t,a]=await Promise.all([db.from('profiles').select('id,name,photo_url,created_at,blocked').order('created_at',{ascending:false}),db.from('tests').select('id,name,description,release_at,duration_minutes,total_questions,total_marks,positive_marks,negative_mcq,negative_numerical,reattempt_limit,leaderboard_enabled,paper_url,enabled,created_at').order('release_at',{ascending:false}),db.from('attempts').select('id,test_id,user_id,status,score,max_score,correct_count,incorrect_count,unanswered_count,started_at,submitted_at,created_at,time_taken_seconds').order('created_at',{ascending:false})]);if(p.error)throw p.error;if(t.error)throw t.error;if(a.error)throw a.error;studentsCache=p.data||[];testsCache=t.data||[];attemptsCache=a.data||[]}
function attemptsForUser(id){return attemptsCache.filter(a=>String(a.user_id)===String(id))}
function attemptsForTest(id){return attemptsCache.filter(a=>String(a.test_id)===String(id))}
function testsTable(rows){if(!rows.length)return '<div class="table-wrap"><div class="empty">No tests yet. Create your first test above.</div></div>';return `<div class="table-wrap"><table><thead><tr><th>Test</th><th>Release</th><th>Duration</th><th>Questions</th><th>Attempts</th><th>Re-attempts</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>{const [st,cl]=statusFor(x);const ac=attemptsForTest(x.id).length;return `<tr><td><b>${esc(x.name)}</b><small>${esc(x.description||'')}</small></td><td>${formatDate(x.release_at)}</td><td>${x.duration_minutes} min</td><td>${x.total_questions}</td><td>${ac}</td><td>${Number(x.reattempt_limit||0)}</td><td><span class="pill ${cl}">${st}</span></td><td class="actions"><button class="mini js-edit-test" data-id="${x.id}">Edit</button><button class="mini js-toggle" data-id="${x.id}" data-enabled="${x.enabled!==false}">${x.enabled===false?'Enable':'Disable'}</button><button class="mini danger-btn js-delete" data-id="${x.id}" data-name="${esc(x.name)}">Delete</button></td></tr>`}).join('')}</tbody></table></div>`}
function studentTable(rows){if(!rows.length)return '<div class="table-wrap"><div class="empty">No students yet.</div></div>';return `<div class="table-wrap"><table><thead><tr><th>Student</th><th>Attempts</th><th>Submitted</th><th>Best score</th><th>Last activity</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(s=>{const aa=attemptsForUser(s.id),sub=aa.filter(a=>a.status==='submitted'),best=sub.reduce((m,a)=>Math.max(m,Number(a.score??-Infinity)), -Infinity);const last=aa[0]?.created_at||s.created_at;return `<tr><td><div class="student-cell">${s.photo_url?`<img src="${esc(s.photo_url)}" alt="">`:''}<span><b>${esc(s.name||'Unnamed')}</b><small>${esc(s.id)}</small></span></div></td><td>${aa.length}</td><td>${sub.length}</td><td>${Number.isFinite(best)?best:'—'}</td><td>${formatDate(last)}</td><td><span class="pill ${s.blocked?'disabled':'released'}">${s.blocked?'BLOCKED':'ACTIVE'}</span></td><td><button class="mini js-edit-student" data-id="${esc(s.id)}">Manage</button></td></tr>`}).join('')}</tbody></table></div>`}
function attemptsTable(rows){if(!rows.length)return '<div class="table-wrap"><div class="empty">No attempts yet.</div></div>';return `<div class="table-wrap"><table><thead><tr><th>Student</th><th>Test</th><th>Status</th><th>Score</th><th>Correct / Wrong</th><th>Time</th><th>Started</th></tr></thead><tbody>${rows.map(a=>`<tr><td><b>${esc(studentsCache.find(s=>String(s.id)===String(a.user_id))?.name||a.user_id?.slice(0,8)||'Unknown')}</b><small>${esc(a.user_id||'')}</small></td><td>${esc(testName(a.test_id))}</td><td>${esc(a.status)}</td><td>${a.score??'—'}/${a.max_score??'—'}</td><td>${a.correct_count??'—'} / ${a.incorrect_count??'—'}</td><td>${a.time_taken_seconds?Math.round(a.time_taken_seconds/60)+' min':'—'}</td><td>${formatDate(a.started_at)}</td></tr>`).join('')}</tbody></table></div>`}
function testName(id){return testsCache.find(x=>String(x.id)===String(id))?.name||String(id)}
function analyticsView(){const submitted=attemptsCache.filter(a=>a.status==='submitted');const avg=submitted.length?submitted.reduce((s,a)=>s+Number(a.score||0),0)/submitted.length:0;const completedTests=new Set(submitted.map(a=>a.test_id)).size;const active=studentsCache.filter(s=>!s.blocked).length;const blocked=studentsCache.filter(s=>s.blocked).length;const rows=testsCache.map(t=>{const a=attemptsForTest(t.id),sub=a.filter(x=>x.status==='submitted'),av=sub.length?sub.reduce((s,x)=>s+Number(x.score||0),0)/sub.length:0;return {t,a,sub,av}}).sort((a,b)=>b.a.length-a.a.length);return `<div class="cards"><div class="card"><div class="label">ACTIVE STUDENTS</div><div class="value">${active}</div><small>${blocked} blocked</small></div><div class="card"><div class="label">SUBMITTED ATTEMPTS</div><div class="value">${submitted.length}</div><small>${attemptsCache.length} total sessions</small></div><div class="card"><div class="label">AVG SCORE</div><div class="value">${avg.toFixed(1)}</div><small>Across submitted attempts</small></div><div class="card"><div class="label">TESTS WITH RESULTS</div><div class="value">${completedTests}</div><small>At least one submission</small></div></div><div class="section-head"><h2>Test performance</h2></div><div class="table-wrap"><table><thead><tr><th>Test</th><th>Attempts</th><th>Submitted</th><th>Avg score</th><th>Completion</th><th>Release</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.t.name)}</b></td><td>${r.a.length}</td><td>${r.sub.length}</td><td>${r.sub.length?r.av.toFixed(1):'—'}</td><td>${r.a.length?Math.round(r.sub.length/r.a.length*100)+'%':'—'}</td><td>${formatDate(r.t.release_at)}</td></tr>`).join('')}</tbody></table></div>`}
async function loadOverview(){await loadAll();const submitted=attemptsCache.filter(x=>x.status==='submitted');const avg=submitted.length?submitted.reduce((s,x)=>s+Number(x.score||0),0)/submitted.length:0;const next=testsCache.filter(t=>t.enabled!==false&&new Date(t.release_at)>new Date()).sort((a,b)=>new Date(a.release_at)-new Date(b.release_at))[0];$('#content').innerHTML=`<div class="cards"><div class="card"><div class="label">STUDENTS</div><div class="value">${studentsCache.length}</div><small>${studentsCache.filter(s=>!s.blocked).length} active · ${studentsCache.filter(s=>s.blocked).length} blocked</small></div><div class="card"><div class="label">TESTS</div><div class="value">${testsCache.length}</div><small>${testsCache.filter(t=>t.enabled!==false).length} enabled</small></div><div class="card"><div class="label">ATTEMPTS</div><div class="value">${attemptsCache.length}</div><small>${submitted.length} submitted</small></div><div class="card"><div class="label">AVG SCORE</div><div class="value">${avg.toFixed(1)}</div><small>Submitted attempts</small></div></div><div class="hero command-hero"><div><div class="eyebrow">CONTROL CENTER · LIVE</div><h2>${next?`Next: ${esc(next.name)}`:'No upcoming test scheduled'}</h2><p class="muted">${next?`${formatDate(next.release_at)} · ${next.duration_minutes} minutes · ${next.total_questions} questions`:'Create a test and set its exact release time.'}</p></div><div class="hero-actions"><button class="primary" onclick="openCreateModal()">+ Create Test</button><button class="ghost" onclick="setView('analytics')">View analytics</button></div></div><div class="section-head"><h2>Tests at a glance</h2><button class="ghost" onclick="setView('tests')">Manage tests →</button></div>${testsTable(testsCache.slice(0,8))}<div class="section-head"><h2>Latest student activity</h2><button class="ghost" onclick="setView('attempts')">Open attempts →</button></div>${attemptsTable(attemptsCache.slice(0,10))}`}
async function loadTests(){await loadAll();$('#content').innerHTML=`<div class="hero"><div><div class="eyebrow">TEST MANAGEMENT</div><h2>Tests & schedules</h2><p class="muted">Edit names, release time, duration, marking, PDFs, re-attempt policy, leaderboard visibility, or availability without recreating the test.</p></div><button class="primary" onclick="openCreateModal()">+ New Test</button></div>${testsTable(testsCache)}`}
async function loadStudents(){await loadAll();$('#content').innerHTML=`<div class="hero"><div><div class="eyebrow">STUDENT DIRECTORY</div><h2>Students</h2><p class="muted">Rename accounts, inspect activity, or block access instantly.</p></div></div>${studentTable(studentsCache)}`}
async function loadAttempts(){await loadAll();$('#content').innerHTML=`<div class="hero"><div><div class="eyebrow">ATTEMPT LOG</div><h2>Attempts & scores</h2><p class="muted">See submitted, in-progress and abandoned sessions with timing data.</p></div></div>${attemptsTable(attemptsCache)}`}
async function render(){try{if(current==='overview')await loadOverview();else if(current==='tests')await loadTests();else if(current==='students')await loadStudents();else if(current==='attempts')await loadAttempts();else if(current==='analytics'){await loadAll();$('#content').innerHTML=analyticsView()}wireDynamicButtons()}catch(e){$('#content').innerHTML=`<div class="hero"><h2 class="danger">Dashboard error</h2><p class="muted">${esc(e.message||e)}</p></div>`}}
function setView(v){current=v;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const btn=document.querySelector(`.nav[data-view="${v}"]`);$('#viewTitle').textContent=btn?.textContent||v;render()}
function resetTestForm(){const f=$('#testForm');f.reset();$('#testForm').dataset.editId='';$('#testModalEyebrow').textContent='TEST BUILDER';$('#testModalTitle').textContent='Create new test';$('#createTestBtn').textContent='Create & Schedule Test';$('#paperHint').textContent='Required when creating a test. Leave empty while editing to keep the current paper.';$('#keyHint').textContent='Required when creating a test. Leave empty while editing to keep the current key.';hide('#uploadProgress');hide('#formError')}
function openCreateModal(){resetTestForm();const d=new Date(Date.now()+3600000);d.setSeconds(0,0);$('#testForm').elements.namedItem('release').value=localInput(d.toISOString());$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true');resetTestForm()}
function openEditTest(id){const t=testsCache.find(x=>String(x.id)===String(id));if(!t)return;const f=$('#testForm');f.dataset.editId=t.id;f.elements.namedItem('name').value=t.name||'';f.elements.namedItem('description').value=t.description||'';f.elements.namedItem('duration').value=t.duration_minutes||180;f.elements.namedItem('release').value=localInput(t.release_at);f.elements.namedItem('questions').value=t.total_questions||75;f.elements.namedItem('totalMarks').value=t.total_marks??300;f.elements.namedItem('reattempts').value=t.reattempt_limit??0;f.elements.namedItem('leaderboard').value=String(t.leaderboard_enabled!==false);f.elements.namedItem('positive').value=t.positive_marks??4;f.elements.namedItem('negativeA').value=t.negative_mcq??1;f.elements.namedItem('negativeB').value=t.negative_numerical??1;f.elements.namedItem('paper').required=false;f.elements.namedItem('key').required=false;$('#testModalEyebrow').textContent='TEST EDITOR';$('#testModalTitle').textContent='Edit test';$('#createTestBtn').textContent='Save test changes';$('#paperHint').textContent=t.paper_url?'Current paper is kept unless you choose a replacement.':'No paper attached yet.';$('#keyHint').textContent='Current answer key is kept unless you choose a replacement.';hide('#formError');$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
async function uploadPdf(file,path){const {error}=await db.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:true});if(error)throw error;return path}
async function createOrUpdateTest(e){e.preventDefault();const f=new FormData(e.target),editId=e.target.dataset.editId||'';const name=String(f.get('name')||'').trim(),releaseLocal=f.get('release');const paper=f.get('paper'),key=f.get('key');const questions=Number(f.get('questions')),totalMarks=Number(f.get('totalMarks')),positive=Number(f.get('positive')),negativeA=Number(f.get('negativeA')),negativeB=Number(f.get('negativeB')),duration=Number(f.get('duration')),reattempts=Number(f.get('reattempts')),leaderboard=String(f.get('leaderboard'))==='true';if(!name)throw new Error('Enter a test name.');if(!Number.isFinite(questions)||questions<1||questions%3!==0)throw new Error('Questions must be a positive number divisible by 3 for the current PCM CBT.');if(!Number.isFinite(duration)||duration<1)throw new Error('Enter a valid duration.');if(!Number.isFinite(totalMarks)||totalMarks<=0)throw new Error('Enter valid total marks.');if([positive,negativeA,negativeB].some(v=>!Number.isFinite(v)||v<0))throw new Error('Enter valid marking values.');if(!Number.isInteger(reattempts)||reattempts<0||reattempts>50)throw new Error('Re-attempts must be a whole number from 0 to 50.');const releaseAt=new Date(releaseLocal);if(Number.isNaN(releaseAt.getTime()))throw new Error('Invalid release date/time.');$('#createTestBtn').disabled=true;show('#uploadProgress');$('.progress-bar').style.width='15%';$('#uploadProgress span').textContent=editId?'Saving test…':'Creating test…';let id=editId;
  if(!editId){if(!paper||!key)throw new Error('Please select both PDF files when creating a test.');const {data:test,error}=await db.from('tests').insert({name,description:String(f.get('description')||'').trim(),release_at:releaseAt.toISOString(),duration_minutes:duration,total_questions:questions,total_marks:totalMarks,positive_marks:positive,negative_mcq:negativeA,negative_numerical:negativeB,reattempt_limit:reattempts,leaderboard_enabled:leaderboard,enabled:true}).select('id').single();if(error)throw error;id=test.id;try{const base=`tests/${id}`;$('.progress-bar').style.width='35%';$('#uploadProgress span').textContent='Uploading question paper…';const paperPath=await uploadPdf(paper,`${base}/question-paper.pdf`);$('.progress-bar').style.width='65%';$('#uploadProgress span').textContent='Uploading answer key…';const keyPath=await uploadPdf(key,`${base}/answer-key.pdf`);const {error:ue}=await db.from('tests').update({paper_url:paperPath}).eq('id',id);if(ue)throw ue;const {error:ke}=await db.from('test_answer_keys').upsert({test_id:id,answer_key:{storage_path:keyPath,filename:key.name,mime:'application/pdf'}},{onConflict:'test_id'});if(ke)throw ke;}catch(err){await db.from('tests').delete().eq('id',id);throw err}}
  else {const {error}=await db.from('tests').update({name,description:String(f.get('description')||'').trim(),release_at:releaseAt.toISOString(),duration_minutes:duration,total_questions:questions,total_marks:totalMarks,positive_marks:positive,negative_mcq:negativeA,negative_numerical:negativeB,reattempt_limit:reattempts,leaderboard_enabled:leaderboard}).eq('id',id);if(error)throw error;if(paper){await uploadPdf(paper,`tests/${id}/question-paper.pdf`);await db.from('tests').update({paper_url:`tests/${id}/question-paper.pdf`}).eq('id',id)}if(key){const keyPath=`tests/${id}/answer-key.pdf`;await uploadPdf(key,keyPath);const {error:ke}=await db.from('test_answer_keys').upsert({test_id:id,answer_key:{storage_path:keyPath,filename:key.name,mime:'application/pdf'}},{onConflict:'test_id'});if(ke)throw ke}}
  $('.progress-bar').style.width='100%';toast(editId?'Test updated ✓':'Test created and scheduled ✓');closeModal();await render()}
async function toggleTest(id,wasEnabled){const {error}=await db.from('tests').update({enabled:!wasEnabled}).eq('id',id);if(error)throw error;toast(wasEnabled?'Test disabled':'Test enabled');render()}
async function deleteTest(id,name){if(!confirm(`Delete “${name}”? This removes the test, answer key and linked attempts.`))return;const {error}=await db.from('tests').delete().eq('id',id);if(error){toast(error.message);return}await db.storage.from(BUCKET).remove([`tests/${id}/question-paper.pdf`,`tests/${id}/answer-key.pdf`]);toast('Test deleted');render()}
function openStudent(id){const s=studentsCache.find(x=>String(x.id)===String(id));if(!s)return;const f=$('#studentForm');f.id.value=s.id;f.name.value=s.name||'';f.blocked.value=String(!!s.blocked);const aa=attemptsForUser(s.id),sub=aa.filter(a=>a.status==='submitted'),best=sub.reduce((m,a)=>Math.max(m,Number(a.score??-Infinity)),-Infinity);$('#studentStats').innerHTML=`<div><b>${aa.length}</b><span>Total attempts</span></div><div><b>${sub.length}</b><span>Submitted</span></div><div><b>${Number.isFinite(best)?best:'—'}</b><span>Best score</span></div>`;hide('#studentFormError');$('#studentModal').classList.remove('hidden');$('#studentModal').setAttribute('aria-hidden','false')}
function closeStudent(){hide('#studentModal');$('#studentModal').setAttribute('aria-hidden','true')}
async function saveStudent(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id'),name=String(f.get('name')||'').trim(),blocked=f.get('blocked')==='true';if(!name)throw new Error('Student name cannot be empty.');const {data,error}=await db.rpc('admin_update_student',{p_user_id:id,p_name:name,p_blocked:blocked});if(error)throw error;toast(blocked?'Student blocked':'Student updated');closeStudent();await render()}
window.openCreateModal=openCreateModal;window.openEditTest=openEditTest;window.toggleTest=toggleTest;window.deleteTest=deleteTest;window.setView=setView;
function wireDynamicButtons(){document.querySelectorAll('.js-edit-test').forEach(b=>b.addEventListener('click',()=>openEditTest(Number(b.dataset.id))));document.querySelectorAll('.js-toggle').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await toggleTest(Number(b.dataset.id),b.dataset.enabled==='true')}catch(e){toast(e.message||String(e));b.disabled=false}}));document.querySelectorAll('.js-delete').forEach(b=>b.addEventListener('click',()=>deleteTest(Number(b.dataset.id),b.dataset.name||'this test')));document.querySelectorAll('.js-edit-student').forEach(b=>b.addEventListener('click',()=>openStudent(b.dataset.id)))}
function safeOpenCreateModal(){openCreateModal()}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#googleBtn').addEventListener('click',signIn);$('#refresh').addEventListener('click',()=>{toast('Refreshing…');render()});$('#newTestTop').addEventListener('click',safeOpenCreateModal);$('#logout').addEventListener('click',async()=>{await db.auth.signOut();location.reload()});$('#testForm').addEventListener('submit',async e=>{try{hide('#formError');await createOrUpdateTest(e)}catch(err){$('#formError').textContent=err.message||String(err);show('#formError');$('#createTestBtn').disabled=false;hide('#uploadProgress')}});$('#studentForm').addEventListener('submit',async e=>{try{hide('#studentFormError');await saveStudent(e)}catch(err){$('#studentFormError').textContent=err.message||String(err);show('#studentFormError')}});document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.querySelectorAll('[data-close-student]').forEach(x=>x.addEventListener('click',closeStudent));db.auth.onAuthStateChange((_e,s)=>{session=s});(async()=>{try{if(await requireAdmin())await render()}catch(e){hide('#loading');show('#login');$('#loginError').textContent=e.message||String(e);show('#loginError')}})();
