'use strict';
const SUPABASE_URL='https://grgxaewilmfyvndkcfim.supabase.co';
const SUPABASE_KEY='sb_publishable_aiJYxr3AYoeZHBXwIoXaaQ_gIfHxV2s';
const BUCKET='test-pdfs';
const {createClient}=window.supabase;
const db=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s); let session=null,current='overview',testsCache=[],studentsCache=[],attemptsCache=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(id){$(id).classList.remove('hidden')} function hide(id){$(id).classList.add('hidden')}
function toast(msg){$('#toast').textContent=msg;show('#toast');clearTimeout(window.__toast);window.__toast=setTimeout(()=>hide('#toast'),3000)}
function formatDate(v){return v?new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—'}
function statusFor(t){if(t.archived)return ['ARCHIVED','disabled'];if(t.enabled===false)return ['DISABLED','disabled'];return new Date(t.release_at)<=new Date()?['RELEASED','released']:['SCHEDULED','scheduled']}
function localInput(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return '';return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
async function requireAdmin(){const {data,error}=await db.auth.getSession();if(error)throw error;session=data.session;if(!session){hide('#loading');show('#login');return false}const {data:isAdmin,error:e}=await db.rpc('is_admin');if(e)throw e;if(!isAdmin){hide('#loading');show('#login');$('#loginError').textContent='This Google account is not an admin.';show('#loginError');return false}hide('#loading');hide('#login');show('#app');$('#adminIdentity').textContent=session.user.email||session.user.user_metadata?.full_name||'Admin';return true}
async function signIn(){$('#googleBtn').disabled=true;hide('#loginError');const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(error){$('#loginError').textContent=error.message;show('#loginError');$('#googleBtn').disabled=false}}
async function loadAll(){const [p,t,a]=await Promise.all([db.from('profiles').select('id,name,photo_url,created_at,blocked').order('created_at',{ascending:false}),db.from('tests').select('id,name,description,release_at,duration_minutes,total_questions,total_marks,positive_marks,negative_mcq,negative_numerical,reattempt_limit,leaderboard_enabled,paper_url,enabled,archived,created_at,subject_order').order('release_at',{ascending:false}),db.from('attempts').select('id,test_id,user_id,status,score,max_score,correct_count,incorrect_count,unanswered_count,started_at,submitted_at,created_at,time_taken_seconds,expires_at').order('created_at',{ascending:false})]);if(p.error)throw p.error;if(t.error)throw t.error;if(a.error)throw a.error;studentsCache=p.data||[];testsCache=t.data||[];attemptsCache=a.data||[]}
function attemptsForUser(id){return attemptsCache.filter(a=>String(a.user_id)===String(id))}
function attemptsForTest(id){return attemptsCache.filter(a=>String(a.test_id)===String(id))}
function testsTable(rows){if(!rows.length)return '<div class="table-wrap"><div class="empty">No tests yet. Create your first test above.</div></div>';return `<div class="table-wrap"><table><thead><tr><th>Test</th><th>Release</th><th>Duration</th><th>Questions</th><th>Attempts</th><th>Re-attempts</th><th>Leaderboard</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>{const [st,cl]=statusFor(x);const ac=attemptsForTest(x.id).length;return `<tr><td><b>${esc(x.name)}</b><small>${esc(x.description||'')}</small></td><td>${formatDate(x.release_at)}</td><td>${x.duration_minutes} min</td><td>${x.total_questions}</td><td>${ac}</td><td>${Number(x.reattempt_limit||0)}</td><td>${x.leaderboard_enabled!==false?'ON':'OFF'}</td><td><span class="pill ${cl}">${st}</span></td><td class="actions"><button class="mini js-edit-test" data-id="${x.id}">Edit</button>${x.archived?'':'<button class="mini js-toggle" data-id="'+x.id+'" data-enabled="'+(x.enabled!==false)+'">'+(x.enabled===false?'Enable':'Disable')+'</button>'}${x.archived?'':'<button class="mini danger-btn js-archive" data-id="'+x.id+'" data-name="'+esc(x.name)+'">Archive</button>'}<button class="mini purge js-purge" data-id="${x.id}" data-name="${esc(x.name)}" title="Delete from database forever">Delete forever</button></td></tr>`}).join('')}</tbody></table></div>`}
function studentTable(rows){if(!rows.length)return '<div class="table-wrap"><div class="empty">No students yet.</div></div>';return `<div class="table-wrap"><table><thead><tr><th>Student</th><th>Attempts</th><th>Submitted</th><th>Best score</th><th>Last activity</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(s=>{const aa=attemptsForUser(s.id),sub=aa.filter(a=>a.status==='submitted'),best=sub.reduce((m,a)=>Math.max(m,Number(a.score??-Infinity)), -Infinity);const last=aa[0]?.created_at||s.created_at;return `<tr><td><div class="student-cell">${s.photo_url?`<img src="${esc(s.photo_url)}" alt="">`:''}<span><b>${esc(s.name||'Unnamed')}</b><small>${esc(s.id)}</small></span></div></td><td>${aa.length}</td><td>${sub.length}</td><td>${Number.isFinite(best)?best:'—'}</td><td>${formatDate(last)}</td><td><span class="pill ${s.blocked?'disabled':'released'}">${s.blocked?'BLOCKED':'ACTIVE'}</span></td><td><button class="mini js-edit-student" data-id="${esc(s.id)}">Manage</button></td></tr>`}).join('')}</tbody></table></div>`}
function attemptsTable(rows){if(!rows.length)return '<div class="table-wrap"><div class="empty">No attempts found.</div></div>';return `<div class="table-wrap"><table><thead><tr><th>Student</th><th>Test</th><th>Status</th><th>Score</th><th>Correct / Wrong</th><th>Time</th><th>Started</th><th>Actions</th></tr></thead><tbody>${rows.map(a=>{const st=a.status,pc=st==='submitted'?'released':st==='in_progress'?'scheduled':'disabled';return `<tr><td><b>${esc(studentsCache.find(s=>String(s.id)===String(a.user_id))?.name||a.user_id?.slice(0,8)||'Unknown')}</b><small>${esc(a.user_id||'')}</small></td><td>${esc(testName(a.test_id))}</td><td><span class="pill ${pc}">${esc(st)}</span></td><td>${a.score??'—'}/${a.max_score??'—'}</td><td>${a.correct_count??'—'} / ${a.incorrect_count??'—'}</td><td>${a.time_taken_seconds?Math.round(a.time_taken_seconds/60)+' min':'—'}</td><td>${formatDate(a.started_at)}</td><td class="actions">${st==='in_progress'?`<button class="mini js-force" data-id="${a.id}">Force submit</button>`:''}${st==='in_progress'?`<button class="mini danger-btn js-invalidate" data-id="${a.id}">Invalidate</button>`:''}${st==='submitted'?`<button class="mini js-void" data-id="${a.id}" title="Marks it abandoned so it no longer counts as an attempt. Row is kept.">Free attempt</button>`:''}<button class="mini purge js-delete-attempt" data-id="${a.id}" title="Delete this attempt and its answers forever">Delete</button></td></tr>`}).join('')}</tbody></table></div>`}
function testName(id){return testsCache.find(x=>String(x.id)===String(id))?.name||String(id)}
function analyticsView(){const submitted=attemptsCache.filter(a=>a.status==='submitted');const avg=submitted.length?submitted.reduce((s,a)=>s+Number(a.score||0),0)/submitted.length:0;const completedTests=new Set(submitted.map(a=>a.test_id)).size;const active=studentsCache.filter(s=>!s.blocked).length;const blocked=studentsCache.filter(s=>s.blocked).length;const rows=testsCache.map(t=>{const a=attemptsForTest(t.id),sub=a.filter(x=>x.status==='submitted'),av=sub.length?sub.reduce((s,x)=>s+Number(x.score||0),0)/sub.length:0;return {t,a,sub,av}}).sort((a,b)=>b.a.length-a.a.length);return `<div class="cards"><div class="card"><div class="label">ACTIVE STUDENTS</div><div class="value">${active}</div><small>${blocked} blocked</small></div><div class="card"><div class="label">SUBMITTED ATTEMPTS</div><div class="value">${submitted.length}</div><small>${attemptsCache.length} total sessions</small></div><div class="card"><div class="label">AVG SCORE</div><div class="value">${avg.toFixed(1)}</div><small>Across submitted attempts</small></div><div class="card"><div class="label">TESTS WITH RESULTS</div><div class="value">${completedTests}</div><small>At least one submission</small></div></div><div class="section-head"><h2>Test performance</h2></div><div class="table-wrap"><table><thead><tr><th>Test</th><th>Attempts</th><th>Submitted</th><th>Avg score</th><th>Completion</th><th>Release</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.t.name)}</b></td><td>${r.a.length}</td><td>${r.sub.length}</td><td>${r.sub.length?r.av.toFixed(1):'—'}</td><td>${r.a.length?Math.round(r.sub.length/r.a.length*100)+'%':'—'}</td><td>${formatDate(r.t.release_at)}</td></tr>`).join('')}</tbody></table></div>`}
async function loadOverview(){await loadAll();const submitted=attemptsCache.filter(x=>x.status==='submitted');const avg=submitted.length?submitted.reduce((s,x)=>s+Number(x.score||0),0)/submitted.length:0;const next=testsCache.filter(t=>t.enabled!==false&&new Date(t.release_at)>new Date()).sort((a,b)=>new Date(a.release_at)-new Date(b.release_at))[0];$('#content').innerHTML=`<div class="cards"><div class="card"><div class="label">STUDENTS</div><div class="value">${studentsCache.length}</div><small>${studentsCache.filter(s=>!s.blocked).length} active · ${studentsCache.filter(s=>s.blocked).length} blocked</small></div><div class="card"><div class="label">TESTS</div><div class="value">${testsCache.length}</div><small>${testsCache.filter(t=>t.enabled!==false).length} enabled</small></div><div class="card"><div class="label">ATTEMPTS</div><div class="value">${attemptsCache.length}</div><small>${submitted.length} submitted</small></div><div class="card"><div class="label">AVG SCORE</div><div class="value">${avg.toFixed(1)}</div><small>Submitted attempts</small></div></div><div class="hero command-hero"><div><div class="eyebrow">CONTROL CENTER · LIVE</div><h2>${next?`Next: ${esc(next.name)}`:'No upcoming test scheduled'}</h2><p class="muted">${next?`${formatDate(next.release_at)} · ${next.duration_minutes} minutes · ${next.total_questions} questions`:'Create a test and set its exact release time.'}</p></div><div class="hero-actions"><button class="primary" onclick="openCreateModal()">+ Create Test</button><button class="ghost" onclick="setView('analytics')">View analytics</button></div></div><div class="section-head"><h2>Tests at a glance</h2><button class="ghost" onclick="setView('tests')">Manage tests →</button></div>${testsTable(testsCache.slice(0,8))}<div class="section-head"><h2>Latest student activity</h2><button class="ghost" onclick="setView('attempts')">Open attempts →</button></div>${attemptsTable(attemptsCache.slice(0,10))}`}
async function loadTests(){await loadAll();$('#content').innerHTML=`<div class="hero"><div><div class="eyebrow">TEST MANAGEMENT</div><h2>Tests & schedules</h2><p class="muted">Edit names, release time, duration, marking, PDFs, re-attempt policy, leaderboard visibility, or availability without recreating the test.</p></div><button class="primary" onclick="openCreateModal()">+ New Test</button></div>${testsTable(testsCache)}`}
async function loadStudents(){await loadAll();$('#content').innerHTML=`<div class="hero"><div><div class="eyebrow">STUDENT DIRECTORY</div><h2>Students</h2><p class="muted">Rename accounts, inspect activity, or block access instantly.</p></div></div>${studentTable(studentsCache)}`}
async function loadAttempts(){await loadAll();const pre=window.__attemptSearch||'';window.__attemptSearch='';$('#content').innerHTML=`<div class="hero"><div><div class="eyebrow">ATTEMPT LOG</div><h2>Attempts & scores</h2><p class="muted">Search, then free an attempt (student can retake) or delete it permanently. Use <b>Manage</b> on a student to grant extra attempts.</p></div></div><div class="grant-grid" style="grid-template-columns:1.4fr 1.2fr .8fr;margin:0 0 12px"><input id="atSearch" placeholder="Search student name or ID…" value="${esc(pre)}"><select id="atTest"><option value="">All tests</option>${testsCache.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select><select id="atStatus"><option value="">All statuses</option><option value="submitted">submitted</option><option value="in_progress">in_progress</option><option value="abandoned">abandoned</option></select></div><div id="attemptsBody"></div>`;['#atSearch','#atTest','#atStatus'].forEach(x=>$(x).addEventListener(x==='#atSearch'?'input':'change',refreshAttemptsBody));refreshAttemptsBody()}
function refreshAttemptsBody(){const q=($('#atSearch')?.value||'').trim().toLowerCase(),t=$('#atTest')?.value||'',st=$('#atStatus')?.value||'';const rows=attemptsCache.filter(a=>{if(t&&String(a.test_id)!==t)return false;if(st&&a.status!==st)return false;if(q){const nm=(studentsCache.find(s=>String(s.id)===String(a.user_id))?.name||'').toLowerCase();if(!nm.includes(q)&&!String(a.user_id||'').toLowerCase().includes(q))return false}return true});const box=$('#attemptsBody');if(!box)return;box.innerHTML=`<p class="muted" style="margin:0 0 8px">${rows.length} of ${attemptsCache.length} attempts</p>`+attemptsTable(rows.slice(0,300))+(rows.length>300?'<p class="muted">Showing first 300 — refine the search.</p>':'');wireDynamicButtons()}
async function loadAdmins(){const {data,error}=await db.rpc('admin_list_users');if(error)throw error;const rows=data||[];$('#content').innerHTML=`<div class="admin-banner"><div><b>Administrator access</b><span>Only administrators can change roles. The database enforces the check, so this page cannot grant access by itself.</span></div><span>${rows.filter(r=>r.is_admin).length} admin${rows.filter(r=>r.is_admin).length===1?'':'s'}</span></div><div class="section-head"><div><h2>Accounts</h2><p class="muted">Promote trusted accounts to admin or remove admin access. Email addresses come from the authenticated account.</p></div></div><div class="admin-list">${rows.map(r=>`<div class="admin-row"><div><b>${esc(r.name||'Unnamed')}</b><small>${esc(r.email||'No email')}</small></div><div><small>Joined</small>${formatDate(r.created_at)}</div><div><span class="role-pill ${r.is_admin?'':'user'}">${r.is_admin?'ADMIN':'STUDENT'}</span></div><div><small>Attempts</small>${Number(r.attempts||0)}</div><div class="admin-actions">${String(r.id)===String(session?.user?.id)?'<span class="muted">You</span>':`<button class="mini ${r.is_admin?'danger-outline':''} js-role" data-id="${esc(r.id)}" data-name="${esc(r.name||r.email||'this user')}" data-admin="${r.is_admin?'true':'false'}">${r.is_admin?'Remove admin':'Make admin'}</button>`}</div></div>`).join('')||'<div class="empty">No accounts found.</div>'}</div>`} 
function openAdminRole(id,name,isAdmin){$('#adminModalInfo').textContent=isAdmin?`Remove administrator access from ${name}? They will immediately lose access to the control center.`:`Make ${name} an administrator? They will be able to manage tests, students, attempts and other administrators.`;$('#adminModalError').textContent='';hide('#adminModalError');$('#adminModal').classList.remove('hidden');$('#adminModal').setAttribute('aria-hidden','false');$('#adminModalConfirm').dataset.id=id;$('#adminModalConfirm').dataset.admin=isAdmin?'true':'false';$('#adminModalConfirm').textContent=isAdmin?'Remove admin':'Make admin'}
async function changeAdminRole(id,isAdmin){$('#adminModalConfirm').disabled=true;try{const {error}=await db.rpc('admin_set_admin',{p_user_id:id,p_make_admin:!isAdmin});if(error)throw error;toast(isAdmin?'Admin access removed':'Admin access granted');closeAdminModal();await loadAll();await loadAdmins()}catch(e){$('#adminModalError').textContent=e.message||String(e);show('#adminModalError')}finally{$('#adminModalConfirm').disabled=false}}
function closeAdminModal(){$('#adminModal').classList.add('hidden');$('#adminModal').setAttribute('aria-hidden','true')}
async function loadAudit(){const {data,error}=await db.rpc('admin_audit',{limit_count:200});if(error)throw error;const rows=data||[];$('#content').innerHTML=`<div class="hero"><div><div class="eyebrow">SECURITY & HISTORY</div><h2>Admin audit log</h2><p class="muted">Every sensitive administrative action is recorded here.</p></div></div><div class="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Target</th><th>Details</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${formatDate(r.created_at)}</td><td><b>${esc(r.action)}</b></td><td>${esc(r.target_type||'')} · ${esc(r.target_id||'')}</td><td><code>${esc(JSON.stringify(r.details||{}))}</code></td></tr>`).join('')||'<tr><td colspan="4">No audit events yet.</td></tr>'}</tbody></table></div>`}
async function render(){try{if(current==='overview')await loadOverview();else if(current==='tests')await loadTests();else if(current==='students')await loadStudents();else if(current==='attempts')await loadAttempts();else if(current==='analytics'){await loadAll();$('#content').innerHTML=analyticsView()}else if(current==='audit'){await loadAudit()}else if(current==='admins'){await loadAdmins()}else if(current==='site'){await loadSite()}wireDynamicButtons()}catch(e){$('#content').innerHTML=`<div class="hero"><h2 class="danger">Dashboard error</h2><p class="muted">${esc(e.message||e)}</p></div>`}}
function setView(v){current=v;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const btn=document.querySelector(`.nav[data-view="${v}"]`);$('#viewTitle').textContent=btn?.textContent||v;render()}
function resetTestForm(){const f=$('#testForm');f.reset();const __b=$('#createTestBtn');if(__b)__b.disabled=false;const __u=$('#uploadProgress');if(__u)__u.classList.add('hidden');['duration','questions','totalMarks','positive','negativeA','negativeB','subjectOrder'].forEach(n=>{if(f.elements[n]){f.elements[n].disabled=false;f.elements[n].readOnly=false}});if(f.elements.paper)f.elements.paper.disabled=false;$('#testForm').dataset.editId='';$('#testModalEyebrow').textContent='TEST BUILDER';$('#testModalTitle').textContent='Create new test';$('#createTestBtn').textContent='Create & Schedule Test';$('#paperHint').textContent='Required when creating a test. Leave empty while editing to keep the current paper.';$('#keyHint').textContent='Required when creating a test. Leave empty while editing to keep the current key.';hide('#uploadProgress');hide('#formError')}
function openCreateModal(){resetTestForm();const d=new Date(Date.now()+3600000);d.setSeconds(0,0);$('#testForm').elements.namedItem('release').value=localInput(d.toISOString());$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true');resetTestForm()}
function openEditTest(id){const t=testsCache.find(x=>String(x.id)===String(id));if(!t)return;const f=$('#testForm');f.dataset.editId=t.id;f.elements.namedItem('name').value=t.name||'';f.elements.namedItem('description').value=t.description||'';f.elements.namedItem('duration').value=t.duration_minutes||180;f.elements.namedItem('release').value=localInput(t.release_at);f.elements.namedItem('questions').value=t.total_questions||75;f.elements.namedItem('totalMarks').value=t.total_marks??300;f.elements.namedItem('reattempts').value=t.reattempt_limit??0;f.elements.namedItem('leaderboard').value=String(t.leaderboard_enabled!==false);f.elements.namedItem('subjectOrder').value=t.subject_order||'PCM';f.elements.namedItem('positive').value=t.positive_marks??4;f.elements.namedItem('negativeA').value=t.negative_mcq??1;f.elements.namedItem('negativeB').value=t.negative_numerical??1;f.elements.namedItem('paper').required=false;f.elements.namedItem('key').required=false;const locked=attemptsForTest(t.id).length>0;['duration','questions','totalMarks','positive','negativeA','negativeB','subjectOrder'].forEach(n=>{if(f.elements[n]){f.elements[n].disabled=false;f.elements[n].readOnly=locked}});if(f.elements.subjectOrder)f.elements.subjectOrder.disabled=locked;if(f.elements.paper)f.elements.paper.disabled=locked;$('#testModalEyebrow').textContent=locked?'TEST EDITOR · VERSION LOCKED':'TEST EDITOR';$('#testModalTitle').textContent='Edit test';$('#createTestBtn').textContent='Save test changes';$('#paperHint').textContent=t.paper_url?'Current paper is kept unless you choose a replacement.':'No paper attached yet.';$('#keyHint').textContent='Current answer key is kept unless you choose a replacement.';hide('#formError');$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
async function uploadPdf(file,path){const {error}=await db.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:true});if(error)throw error;return path}
async function createOrUpdateTest(e){e.preventDefault();const f=new FormData(e.target),editId=e.target.dataset.editId||'';const name=String(f.get('name')||'').trim(),releaseLocal=f.get('release');const __real=x=>(x&&typeof x==='object'&&x.size>0)?x:null;const paper=__real(f.get('paper')),key=__real(f.get('key'));const questions=Number(f.get('questions')),totalMarks=Number(f.get('totalMarks')),positive=Number(f.get('positive')),negativeA=Number(f.get('negativeA')),negativeB=Number(f.get('negativeB')),duration=Number(f.get('duration')),reattempts=Number(f.get('reattempts')),leaderboard=String(f.get('leaderboard'))==='true';if(!name)throw new Error('Enter a test name.');if(!Number.isFinite(questions)||questions<1||questions%3!==0)throw new Error('Questions must be a positive number divisible by 3 for the current PCM CBT.');if(!Number.isFinite(duration)||duration<1)throw new Error('Enter a valid duration.');if(!Number.isFinite(totalMarks)||totalMarks<=0)throw new Error('Enter valid total marks.');if([positive,negativeA,negativeB].some(v=>!Number.isFinite(v)||v<0))throw new Error('Enter valid marking values.');if(!Number.isInteger(reattempts)||reattempts<0||reattempts>50)throw new Error('Re-attempts must be a whole number from 0 to 50.');const releaseAt=new Date(releaseLocal);if(Number.isNaN(releaseAt.getTime()))throw new Error('Invalid release date/time.');$('#createTestBtn').disabled=true;show('#uploadProgress');$('.progress-bar').style.width='15%';$('#uploadProgress span').textContent=editId?'Saving test…':'Creating test…';let id=editId;
  if(!editId){if(!paper||!key)throw new Error('Please select both PDF files when creating a test.');const {data:test,error}=await db.from('tests').insert({name,description:String(f.get('description')||'').trim(),release_at:releaseAt.toISOString(),duration_minutes:duration,total_questions:questions,total_marks:totalMarks,positive_marks:positive,negative_mcq:negativeA,negative_numerical:negativeB,reattempt_limit:reattempts,leaderboard_enabled:leaderboard,subject_order:subjectOrder,enabled:true,archived:false}).select('id').single();if(error)throw error;id=test.id;try{const base=`tests/${id}`;$('.progress-bar').style.width='35%';$('#uploadProgress span').textContent='Uploading question paper…';const paperPath=await uploadPdf(paper,`${base}/question-paper.pdf`);$('.progress-bar').style.width='65%';$('#uploadProgress span').textContent='Uploading answer key…';const keyPath=await uploadPdf(key,`${base}/answer-key.pdf`);const {error:ue}=await db.from('tests').update({paper_url:paperPath}).eq('id',id);if(ue)throw ue;const {error:ke}=await db.from('test_answer_keys').upsert({test_id:id,answer_key:{storage_path:keyPath,filename:key.name,mime:'application/pdf'}},{onConflict:'test_id'});if(ke)throw ke;}catch(err){await db.from('tests').delete().eq('id',id);throw err}}
  else {const __locked=attemptsForTest(editId).length>0;const __patch={name,description:String(f.get('description')||'').trim(),release_at:releaseAt.toISOString(),reattempt_limit:reattempts,leaderboard_enabled:leaderboard};if(!__locked)Object.assign(__patch,{subject_order:subjectOrder,duration_minutes:duration,total_questions:questions,total_marks:totalMarks,positive_marks:positive,negative_mcq:negativeA,negative_numerical:negativeB});const {data:__row,error}=await db.from('tests').update(__patch).eq('id',id).select('id');if(error)throw error;if(!__row||!__row.length)throw new Error('Nothing was saved. Your admin account may not have permission to edit tests (check the RLS policy on the tests table).');if(paper){await uploadPdf(paper,`tests/${id}/question-paper.pdf`);const {error:__pe}=await db.from('tests').update({paper_url:`tests/${id}/question-paper.pdf`}).eq('id',id);if(__pe)throw __pe}if(key){const keyPath=`tests/${id}/answer-key.pdf`;await uploadPdf(key,keyPath);const {error:ke}=await db.from('test_answer_keys').upsert({test_id:id,answer_key:{storage_path:keyPath,filename:key.name,mime:'application/pdf'}},{onConflict:'test_id'});if(ke)throw ke}}
  const __kt=String(f.get('keyText')||'').trim();if(__kt){$('#uploadProgress span').textContent='Publishing answer sequence…';const {data:__n,error:__pk}=await db.rpc('publish_answer_key',{p_test_id:Number(id),p_key:__kt});if(__pk)throw new Error('Test saved, but the answer sequence was rejected: '+__pk.message);toast('Answer key published · '+__n+' attempts checked ✓')}
  $('.progress-bar').style.width='100%';toast(editId?'Test updated ✓':'Test created and scheduled ✓');closeModal();await render()}
async function toggleTest(id,wasEnabled){const {error}=await db.from('tests').update({enabled:!wasEnabled}).eq('id',id);if(error)throw error;toast(wasEnabled?'Test disabled':'Test enabled');render()}
async function deleteTest(id,name){if(!confirm(`Archive “${name}”? It will disappear from students but all attempts and files remain safe.`))return;const {error}=await db.rpc('admin_archive_test',{p_test_id:id});if(error){toast(error.message);return}toast('Test archived — data preserved');render()}
function openStudent(id){const s=studentsCache.find(x=>String(x.id)===String(id));if(!s)return;const f=$('#studentForm');f.id.value=s.id;f.name.value=s.name||'';f.blocked.value=String(!!s.blocked);const aa=attemptsForUser(s.id),sub=aa.filter(a=>a.status==='submitted'),best=sub.reduce((m,a)=>Math.max(m,Number(a.score??-Infinity)),-Infinity);$('#studentStats').innerHTML=`<div><b>${aa.length}</b><span>Total attempts</span></div><div><b>${sub.length}</b><span>Submitted</span></div><div><b>${Number.isFinite(best)?best:'—'}</b><span>Best score</span></div>`;$('#grantTest').innerHTML='<option value="">Select a test…</option>'+testsCache.filter(t=>!t.archived).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');hide('#studentFormError');renderStudentAttemptInfo(s.id);$('#studentModal').classList.remove('hidden');$('#studentModal').setAttribute('aria-hidden','false')}
async function grantAttempt(){const uid=$('#studentForm').id.value,tid=$('#grantTest').value,count=Number($('#grantCount').value||1),note=$('#grantNote').value.trim();if(!tid)return toast('Select a test first.');const {error}=await db.rpc('admin_grant_attempt',{p_user_id:uid,p_test_id:Number(tid),p_count:count,p_note:note||null});if(error)return toast(error.message);$('#grantNote').value='';toast(`Granted ${count} extra attempt${count===1?'':'s'} ✓`);await render();await renderStudentAttemptInfo(uid)}
async function forceSubmit(id){const reason=prompt('Reason for force submitting this attempt:','Admin intervention');if(reason===null)return;const {error}=await db.rpc('admin_force_submit',{p_attempt_id:id,p_reason:reason});if(error)return toast(error.message);toast('Attempt force-submitted');await render()}
async function invalidateAttempt(id){const reason=prompt('Reason for invalidating this attempt:','Technical issue / policy');if(reason===null)return;const {error}=await db.rpc('admin_invalidate_attempt',{p_attempt_id:id,p_reason:reason});if(error)return toast(error.message);toast('Attempt invalidated');await render()}
function closeStudent(){hide('#studentModal');$('#studentModal').setAttribute('aria-hidden','true')}
async function saveStudent(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id'),name=String(f.get('name')||'').trim(),blocked=f.get('blocked')==='true';if(!name)throw new Error('Student name cannot be empty.');const {data,error}=await db.rpc('admin_update_student',{p_user_id:id,p_name:name,p_blocked:blocked});if(error)throw error;toast(blocked?'Student blocked':'Student updated');closeStudent();await render()}
window.openCreateModal=openCreateModal;window.openEditTest=openEditTest;window.toggleTest=toggleTest;window.deleteTest=deleteTest;window.setView=setView;
function wireDynamicButtons(){document.querySelectorAll('.js-edit-test').forEach(b=>b.addEventListener('click',()=>openEditTest(Number(b.dataset.id))));document.querySelectorAll('.js-toggle').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await toggleTest(Number(b.dataset.id),b.dataset.enabled==='true')}catch(e){toast(e.message||String(e));b.disabled=false}}));document.querySelectorAll('.js-archive').forEach(b=>b.addEventListener('click',()=>deleteTest(Number(b.dataset.id),b.dataset.name||'this test')));document.querySelectorAll('.js-force').forEach(b=>b.addEventListener('click',()=>forceSubmit(b.dataset.id)));document.querySelectorAll('.js-invalidate').forEach(b=>b.addEventListener('click',()=>invalidateAttempt(b.dataset.id)));document.querySelectorAll('.js-delete').forEach(b=>b.addEventListener('click',()=>deleteTest(Number(b.dataset.id),b.dataset.name||'this test')));document.querySelectorAll('.js-purge').forEach(b=>b.addEventListener('click',()=>openPurge(Number(b.dataset.id),b.dataset.name||'this test')));document.querySelectorAll('.js-edit-student').forEach(b=>b.addEventListener('click',()=>openStudent(b.dataset.id)));document.querySelectorAll('.js-void').forEach(b=>b.addEventListener('click',()=>voidAttempt(b.dataset.id)));document.querySelectorAll('.js-delete-attempt').forEach(b=>b.addEventListener('click',()=>deleteAttempt(b.dataset.id)))}
function safeOpenCreateModal(){openCreateModal()}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.addEventListener('click',e=>{const b=e.target.closest('.js-role');if(b)openAdminRole(b.dataset.id,b.dataset.name,b.dataset.admin==='true');if(e.target.closest('[data-close-admin]'))closeAdminModal()});$('#adminModalConfirm').addEventListener('click',()=>changeAdminRole($('#adminModalConfirm').dataset.id,$('#adminModalConfirm').dataset.admin==='true'));$('#googleBtn').addEventListener('click',signIn);$('#refresh').addEventListener('click',()=>{toast('Refreshing…');render()});$('#newTestTop').addEventListener('click',safeOpenCreateModal);$('#logout').addEventListener('click',async()=>{await db.auth.signOut();location.reload()});$('#testForm').addEventListener('submit',async e=>{try{hide('#formError');await createOrUpdateTest(e)}catch(err){$('#formError').textContent=err.message||String(err);show('#formError');$('#createTestBtn').disabled=false;hide('#uploadProgress')}});$('#grantAttemptBtn').addEventListener('click',grantAttempt);$('#studentForm').addEventListener('submit',async e=>{try{hide('#studentFormError');await saveStudent(e)}catch(err){$('#studentFormError').textContent=err.message||String(err);show('#studentFormError')}});document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.querySelectorAll('[data-close-student]').forEach(x=>x.addEventListener('click',closeStudent));db.auth.onAuthStateChange((_e,s)=>{session=s});(async()=>{try{if(await requireAdmin())await render()}catch(e){hide('#loading');show('#login');$('#loginError').textContent=e.message||String(e);show('#loginError')}})();


/* ---- Delete test forever (UI-only: uses existing tables/storage, no backend change) ---- */
let purgeTarget=null;
function openPurge(id,name){purgeTarget={id,name};const n=attemptsForTest(id).length;$('#purgeInfo').textContent=`This permanently removes “${name}” from the database with its ${n} attempt(s), answers, answer key and uploaded PDFs. This cannot be undone. Use Archive if you only want to hide it.`;$('#purgeInput').value='';$('#purgeGo').disabled=true;hide('#purgeError');show('#purgeModal');setTimeout(()=>$('#purgeInput').focus(),50)}
function closePurge(){hide('#purgeModal');purgeTarget=null}
async function purgeTest(){
  if(!purgeTarget)return;const {id,name}=purgeTarget,btn=$('#purgeGo');btn.disabled=true;btn.textContent='Deleting…';hide('#purgeError');
  try{
    const t=testsCache.find(x=>Number(x.id)===Number(id));
    const paths=[`tests/${id}/question-paper.pdf`,`tests/${id}/answer-key.pdf`];if(t?.paper_url&&!/^https?:/i.test(t.paper_url)&&!paths.includes(t.paper_url))paths.push(t.paper_url);
    const {data,error}=await db.from('tests').delete().eq('id',id).select('id');
    if(error)throw error;
    if(!data||!data.length)throw new Error('The database refused to delete this test (row-level security). Your admin account needs delete permission on the tests table.');
    try{await db.storage.from(BUCKET).remove(paths)}catch(e){console.warn('PDF cleanup skipped:',e.message)}
    closePurge();toast(`“${name}” deleted forever`);render();
  }catch(e){const box=$('#purgeError');box.textContent=e.message||String(e);show('#purgeError')}
  finally{btn.textContent='Delete forever';btn.disabled=!purgeTarget||$('#purgeInput').value.trim().toLowerCase()!==purgeTarget.name.trim().toLowerCase()}
}
$('#purgeInput').addEventListener('input',()=>{$('#purgeGo').disabled=!purgeTarget||$('#purgeInput').value.trim().toLowerCase()!==purgeTarget.name.trim().toLowerCase()});
$('#purgeGo').addEventListener('click',purgeTest);
document.querySelectorAll('[data-close-purge]').forEach(b=>b.addEventListener('click',closePurge));
/* ---- Theme (shared with the student site via localStorage md_theme) ---- */
$('#themeBtn').addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=n;try{localStorage.setItem('md_theme',JSON.stringify(n))}catch(e){}});


/* ---- Site controls: show / hide the public leaderboard (admin only, enforced by the database) ---- */
async function loadSite(){
  let visible=true,known=true;
  try{const {data,error}=await db.rpc('get_leaderboard_visibility');if(error)throw error;visible=data!==false}
  catch(e){known=false}
  const note=known?'':'<p class="muted" style="color:#ff8585">Leaderboard switch is not installed yet. Run <code>sql/LEADERBOARD-VISIBILITY.sql</code> once in the Supabase SQL Editor.</p>';
  $('#content').innerHTML=`<div class="hero"><div><div class="eyebrow">SITE CONTROLS</div><h2>Leaderboard visibility</h2><p class="muted">When hidden, the Rankings section, its menu links and the leaderboard cards disappear from the student site within about 30 seconds. Rankings and scores are not deleted — switch it back on any time.</p>${note}</div></div>
  <div class="admin-banner"><div><b>Leaderboard is currently ${visible?'VISIBLE':'HIDDEN'}</b><span>${visible?'Students can see rankings.':'Students cannot see rankings.'}</span></div>
  <button id="lbToggle" class="${visible?'mini danger-outline':'primary small'}" ${known?'':'disabled'}>${visible?'Hide leaderboard':'Show leaderboard'}</button></div>`;
  const b=$('#lbToggle');
  if(b)b.addEventListener('click',async()=>{
    const next=!visible;
    if(!next&&!confirm('Hide the leaderboard from all students?'))return;
    b.disabled=true;
    try{const {error}=await db.rpc('admin_set_leaderboard_visible',{p_visible:next});if(error)throw error;toast(next?'Leaderboard is now visible':'Leaderboard hidden from students');await loadSite()}
    catch(e){toast(e.message||String(e));b.disabled=false}
  });
}

/* ===== Attempt tools: free / delete attempts, per-student usage, grants ===== */
async function voidAttempt(id){const reason=prompt('Free this attempt? It will be marked abandoned and stop counting toward the student\'s limit (row is kept).\n\nReason:','Admin reset');if(reason===null)return;const {error}=await db.rpc('admin_void_attempt',{p_attempt_id:String(id),p_reason:reason});if(error)return toast(error.message);toast('Attempt freed — student can retake');await render()}
async function deleteAttempt(id){const a=attemptsCache.find(x=>String(x.id)===String(id));const who=studentsCache.find(s=>String(s.id)===String(a?.user_id))?.name||'this student';if(!confirm(`PERMANENTLY delete ${who}'s attempt on “${testName(a?.test_id)}” (${a?.status||'?'}, score ${a?.score??'—'}) and all its answers?\n\nThis cannot be undone. Use “Free attempt” if you only want them to retake.`))return;const {error}=await db.rpc('admin_delete_attempt',{p_attempt_id:String(id),p_reason:'Deleted from admin panel'});if(error)return toast(error.message);toast('Attempt deleted');await render()}
async function resetStudentTest(uid,tid){const name=testName(tid);if(!confirm(`Free ALL of this student's attempts on “${name}”? They will get a completely fresh start (rows are kept as abandoned).`))return;const {data,error}=await db.rpc('admin_reset_student_test',{p_user_id:uid,p_test_id:Number(tid),p_reason:'Reset from student panel'});if(error)return toast(error.message);toast(`Freed ${data} attempt${data===1?'':'s'} ✓`);await render();await renderStudentAttemptInfo(uid)}
async function revokeGrant(gid,uid){if(!confirm('Revoke this extra-attempt grant?'))return;const {error}=await db.rpc('admin_revoke_grant',{p_grant_id:Number(gid)});if(error)return toast(error.message);toast('Grant revoked');await render();await renderStudentAttemptInfo(uid)}
async function renderStudentAttemptInfo(uid){const box=$('#studentAttemptInfo');if(!box)return;box.innerHTML='<p class="muted">Loading attempt usage…</p>';const aa=attemptsForUser(uid),sub=aa.filter(a=>a.status==='submitted'),best=sub.reduce((m,a)=>Math.max(m,Number(a.score??-Infinity)),-Infinity);const st=$('#studentStats');if(st)st.innerHTML=`<div><b>${aa.length}</b><span>Total attempts</span></div><div><b>${sub.length}</b><span>Submitted</span></div><div><b>${Number.isFinite(best)?best:'—'}</b><span>Best score</span></div>`;const {data:grants,error}=await db.rpc('admin_list_grants',{p_user_id:uid});if(error){box.innerHTML=`<p class="error">${esc(error.message)} — run ADMIN-ATTEMPT-TOOLS.sql in Supabase first.</p>`;return}const gl=grants||[];const ids=new Set([...aa.map(a=>String(a.test_id)),...gl.map(g=>String(g.test_id))]);const rows=[...ids].map(tid=>{const t=testsCache.find(x=>String(x.id)===tid);const used=aa.filter(a=>String(a.test_id)===tid&&(a.status==='submitted'||a.status==='in_progress')).length;const allowed=1+Number(t?.reattempt_limit||0);const extra=gl.filter(g=>String(g.test_id)===tid).reduce((n,g)=>n+g.remaining,0);return `<tr><td>${esc(t?.name||tid)}</td><td>${used} / ${allowed}</td><td>${extra}</td><td class="actions">${used?`<button type="button" class="mini danger-btn js-reset-st" data-tid="${tid}">Reset attempts</button>`:''}</td></tr>`}).join('');box.innerHTML=`<div class="eyebrow" style="margin-top:14px">ATTEMPT USAGE</div>${rows?`<div class="table-wrap"><table><thead><tr><th>Test</th><th>Used / base allowed</th><th>Extra left</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`:'<p class="muted">No attempts or grants yet.</p>'}${gl.length?`<div class="eyebrow" style="margin-top:14px">UNUSED EXTRA ATTEMPTS</div><div class="table-wrap"><table><tbody>${gl.map(g=>`<tr><td>${esc(testName(g.test_id))}</td><td>${g.remaining} left</td><td>${esc(g.note||'')}</td><td>${formatDate(g.created_at)}</td><td><button type="button" class="mini danger-btn js-revoke" data-gid="${g.id}">Revoke</button></td></tr>`).join('')}</tbody></table></div>`:''}<div style="margin-top:12px"><button type="button" class="ghost" id="viewStudentAttempts">View all this student's attempts →</button></div>`;box.querySelectorAll('.js-reset-st').forEach(b=>b.addEventListener('click',()=>resetStudentTest(uid,b.dataset.tid)));box.querySelectorAll('.js-revoke').forEach(b=>b.addEventListener('click',()=>revokeGrant(b.dataset.gid,uid)));$('#viewStudentAttempts').addEventListener('click',()=>{window.__attemptSearch=String(uid);closeStudent();setView('attempts')})}


/* ===== Log in as a student (needs the "impersonate" Edge Function, see supabase/functions/impersonate) ===== */
async function impersonateStudent(){
  const f=$('#studentForm'),uid=f.id.value,name=(f.name.value||'this student').trim(),btn=$('#impersonateBtn');
  if(!uid)return;
  if(!confirm(`Log in as “${name}”?\n\nYou will see the student site exactly as they do. Anything you do (starting or submitting a test) is real and is saved on THEIR account. This action is recorded in the audit log.\n\nUse the orange “Return to admin” bar to come back.`))return;
  btn.disabled=true;const old=btn.textContent;btn.textContent='Signing in…';
  try{
    const {data:sd}=await db.auth.getSession();const cur=sd&&sd.session;
    if(!cur)throw new Error('Your admin session expired. Please sign in again.');
    const {data,error}=await db.functions.invoke('impersonate',{body:{user_id:uid}});
    if(error){let m=error.message;try{const j=await error.context.json();if(j&&j.error)m=j.error}catch(_){ }
      if(/not found|Failed to send|404/i.test(m))m='The “impersonate” Edge Function is not deployed yet. Run: supabase functions deploy impersonate';
      throw new Error(m)}
    if(!data||!data.token_hash)throw new Error((data&&data.error)||'No login token returned.');
    sessionStorage.setItem('md_admin_return',JSON.stringify({access_token:cur.access_token,refresh_token:cur.refresh_token,admin_id:cur.user.id,admin_email:cur.user.email,student:name}));
    const {error:ve}=await db.auth.verifyOtp({token_hash:data.token_hash,type:'magiclink'});
    if(ve){sessionStorage.removeItem('md_admin_return');throw ve}
    location.href='../';
  }catch(e){toast(e.message||String(e));btn.disabled=false;btn.textContent=old}
}
$('#impersonateBtn').addEventListener('click',impersonateStudent);
